### ISSUE TITLE
FATAL:  could not access file "experdb_mon": No such file or directory

### ISSUE THREAD

**Issue by prensgold** [experdb/eXperDB-Monitoring#211]
Hi ,

When i want to create extension on patroni cluster ,it's giving error as below.
my steps as below.

[postgres@pgnode01 appdata]$ tar zxvf eXperDB_Server_14_0_9_620_8db2c76.tar.gz 
[postgres@pgnode01 appdata]$ cd eXperDB_Server
[postgres@pgnode01 eXperDB_Server]$ ./install.sh -h 127.0.0.1 -d postgres -p 5432 -U postgres -W postgres-pass
   
   **********************************
   *    __  __            __  ___   *
   *  __\ \/ /___ ___ _ _|  \|   \  *
   * / _ \  /|- _/ _ ) '_| | | ' /  *
   * \___/  \|_| \___|_| | | | ' \  *
   *    /_/\_\           |__/|___/  *
   **********************************
 
Install eXperDB-PGMON Repository
   
Step.1 Create the databse of owner.
Would you like to create the owner of the database pgmon? [y/N/q] y
Running: createuser -h 127.0.0.1 -p 5432 -U postgres -s -P pgmon
Enter password for new role: 
Enter it again: 
 
 
Step.2 Create the databse.
Input Database name(Default : experdb) : 
Would you like to create the database experdb? [y/N/q] y
Running: createdb -h 127.0.0.1 -p 5432 -U postgres -E UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --owner pgmon experdb
 
 
Step.3 Create the schema and tables.
Running: psql -h 127.0.0.1 -p 5432 -U pgmon -d experdb -c "CREATE SCHEMA pgmon;"
Would you like to create schema pgmon in database experdb? [y/N/q] y
CREATE SCHEMA
Generating eXperDB_Repository/pgmon_repository.sql
Running: psql -h 127.0.0.1 -p 5432 -U pgmon -d experdb -f eXperDB_Repository/pgmon_repository.sql
 
 
Step.4 Configure the IP and Port of the server for connecting eXperDB-Monitoring-client.
Input Agent Host(Default : 127.0.0.1) : 
Input Agent Port(Default : 5960) : 
Complete to install eXperDB-PGMON Repository.
no crontab for postgres
------------------------------------------------------------------------------
  Thank you for installation eXperDB(R).

  You can now run eXperDB server with command,
  eXperDBMA/bin/experdbma.sh start
  eXperDBMA_MANAGER/bin/experdbma.sh start
------------------------------------------------------------------------------
[postgres@pgnode01 eXperDB_Server]$ eXperDBMA/bin/experdbma.sh start
   
   **********************************
   *    __  __            __  ___   *
   *  __\ \/ /___ ___ _ _|  \|   \  *
   * / _ \  /|- _/ _ ) '_| | | ' /  *
   * \___/  \|_| \___|_| | | | ' \  *
   *    /_/\_\           |__/|___/  *
   **********************************
   
   [Mon Jan 23 11:34:19 +03 2023] eXperDBMA Server Starting...
   [Mon Jan 23 11:34:20 +03 2023] Booting SUCCESS!!! (PID : 335994)
 
[postgres@pgnode01 eXperDB_Server]$ eXperDBMA_MANAGER/bin/experdbma.sh start
   
   **********************************
   *    __  __            __  ___   *
   *  __\ \/ /___ ___ _ _|  \|   \  *
   * / _ \  /|- _/ _ ) '_| | | ' /  *
   * \___/  \|_| \___|_| | | | ' \  *
   *    /_/\_\           |__/|___/  *
   **********************************
   
   [Mon Jan 23 11:34:29 +03 2023] eXperDBMA_Manager Server Starting...
   [Mon Jan 23 11:34:30 +03 2023] Booting SUCCESS!!! (PID : 336323)
 
[postgres@pgnode01 eXperDB_Server]$ 

[postgres@pgnode02 appdata]$ tar zxvf eXperDB_PGMON_14_0_9_620_8db2c76.tar.gz
[root@pgnode01 ~]# cd /appdata/eXperDB_PGMON_14_0_9_620_8db2c76/
[root@pgnode01 eXperDB_PGMON_14_0_9_620_8db2c76]# ls -ltr
total 660
-rw-rw-r-- 1 postgres postgres   5199 Mar 11  2021 Korean_License.txt
-rw-rw-r-- 1 postgres postgres 199026 Mar 11  2021 Korean_License.rtf
-rw-rw-r-- 1 postgres postgres    204 Mar 11  2021 experdb_pgmon.control
-rw-rw-r-- 1 postgres postgres  44412 Mar 11  2021 experdb_pgmon.c
-rw-rw-r-- 1 postgres postgres   5754 Jul 16  2021 uninstall.sh
-rw-rw-r-- 1 postgres postgres    609 Dec 21 11:25 Makefile
-rw-rw-r-- 1 postgres postgres   2272 Dec 21 11:25 experdb_pgmon--unpackaged--1.1.sql
-rw-rw-r-- 1 postgres postgres   4425 Dec 21 11:25 experdb_pgmon--1.1.sql
-rw-rw-r-- 1 postgres postgres 233048 Jan 23 11:38 experdb_pgmon.o
-rwxrwxr-x 1 postgres postgres 125504 Jan 23 11:38 experdb_pgmon.so
-rw-rw-r-- 1 postgres postgres  30504 Jan 23 11:38 experdb_pgmon.bc
[root@pgnode01 eXperDB_PGMON_14_0_9_620_8db2c76]# export PATH=$PATH:/usr/pgsql-14/bin
[root@pgnode01 eXperDB_PGMON_14_0_9_620_8db2c76]# make USE_PGXS=1 install
/usr/bin/mkdir -p '/usr/pgsql-14/lib'
/usr/bin/mkdir -p '/usr/pgsql-14/share/extension'
/usr/bin/mkdir -p '/usr/pgsql-14/share/extension'
/usr/bin/install -c -m 755  experdb_pgmon.so '/usr/pgsql-14/lib/experdb_pgmon.so'
/usr/bin/install -c -m 644 .//experdb_pgmon.control '/usr/pgsql-14/share/extension/'
/usr/bin/install -c -m 644 .//experdb_pgmon--1.1.sql .//experdb_pgmon--unpackaged--1.1.sql  '/usr/pgsql-14/share/extension/'
/usr/bin/mkdir -p '/usr/pgsql-14/lib/bitcode/experdb_pgmon'
/usr/bin/mkdir -p '/usr/pgsql-14/lib/bitcode'/experdb_pgmon/
/usr/bin/install -c -m 644 experdb_pgmon.bc '/usr/pgsql-14/lib/bitcode'/experdb_pgmon/./
cd '/usr/pgsql-14/lib/bitcode' && /usr/bin/llvm-lto -thinlto -thinlto-action=thinlink -o experdb_pgmon.index.bc experdb_pgmon/experdb_pgmon.bc
[root@pgnode01 eXperDB_PGMON_14_0_9_620_8db2c76]# 
[root@pgnode01 eXperDB_PGMON_14_0_9_620_8db2c76]# 
[root@pgnode01 eXperDB_PGMON_14_0_9_620_8db2c76]# 

postgres=# \c experdb
You are now connected to database "experdb" as user "postgres".
experdb=# create extension experdb_mon;
ERROR:  could not open extension control file "/usr/pgsql-14/share/extension/experdb_mon.control": No such file or directory
experdb=# exit
[postgres@pgnode01 eXperDB_Server]$ 

Thanks
Sonmez

**Comment by prensgold** [comment]
[postgres@pgnode01 eXperDB_Server]$ ls -ltr /usr/pgsql-14/share/extension/experdb*
-rw-r--r-- 1 root root  204 Jan 23 12:36 /usr/pgsql-14/share/extension/experdb_pgmon.control
-rw-r--r-- 1 root root 2272 Jan 23 12:36 /usr/pgsql-14/share/extension/experdb_pgmon--unpackaged--1.1.sql
-rw-r--r-- 1 root root 4425 Jan 23 12:36 /usr/pgsql-14/share/extension/experdb_pgmon--1.1.sql
[postgres@pgnode01 eXperDB_Server]$

**Comment by 20hyun** [comment]
this seems typo issue in document, try `CREATE EXTENSION experdb_pgmon;`

**Comment by prensgold** [comment]
yes, it worked this code.Thanks.
