### ISSUE TITLE
저장소 파티션 테이블의 키와 인덱스가 생성되지않아 조회 성능 저하

### ISSUE THREAD

**Issue by gogoickgick** [experdb/eXperDB-Monitoring#41]
**Describe the bug**
저장소 파티션 테이블의 키와 인덱스가 생성되지않아 조회 성능 저하

**To Reproduce**
1. 간헐적 재현
2. 배치 작업에서 예외발생시 생성중단
**Expected behavior**
파티션 테이블별 키와 인덱스 생성 및 조회 원활

**Screenshots**

**Desktop (please complete the following information):**
 - Version : 11.5.0.332

**Additional context**
배치 작업시 예외 적용 필요

**Comment by kayform** [comment]
파티션 드랍과 생성 구문 분리 및 재실행으로 Lock에 인한 예외 발생 대비
